version: '3'

services:
  rails: &rails
    build:
      context: .
      dockerfile: ./compose/development/rails/Dockerfile
    image: missionforest_development_rails
    depends_on:
      - mysql
      - redis
    volumes:
      - missionforest_development_rails_sprockets_cache:/rails_sprockets_cache
      - .:/app
    tty: true      
    ports:
      - "3000:3000"
    env_file:
      - ./.envs/.development/.rails
      - ./.envs/.development/.mysql
      - ./.envs/.development/.redis
    command: /start

  redis:
    image: redis:5.0.6-alpine

  mysql:
    image: mysql:5.7.28
    volumes:
      - missionforest_development_mysql_data:/var/lib/mysql
    env_file:
      - ./.envs/.development/.mysql
    
volumes:
  missionforest_development_mysql_data:
  missionforest_development_rails_sprockets_cache: