version: '3'

services:
  rails:
    build:
      context: ./rails
      dockerfile: ./Dockerfile
    links:
      - mysql:mysql
      - redis:redis
    depends_on:
      - mysql
      - redis
    command: sh
    tty: true
    volumes:
      - ./rails:/opt/MissionForest
    ports:
      - "3000:3000"

  redis:
    image: redis:5.0.6-alpine

  mysql:
    image: mysql:5.7.28
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    
volumes:
  mysql_db: