default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  host: <%= ENV["DB_HOST"] %>

development:
  <<: *default
  database: mission-forest_development

test:
  <<: *default
  database: mission-forest_test

production:
  <<: *default
  database: mission-forest_production