development:
  adapter: redis
  url: redis://localhost:6379
  channel_prefix: mission_forest_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: mission_forest_production
