default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  host: <%= ENV["MYSQL_HOST"] %>
  port: <%= ENV["MYSQL_PORT"] %>

development:
  <<: *default
  database: missionforest_development

test:
  <<: *default
  database: missionforest_test

production:
  <<: *default
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: <%= ENV["MYSQL_DATABASE"] %>  