default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("MYSQL_PORT") { 3306 } %>

development:
  <<: *default
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  database: <%= ENV.fetch("MYSQL_DATABASE") { missionforest_development } %>

test:
  <<: *default
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  database: <%= ENV.fetch("MYSQL_DATABASE") { missionforest_test } %>

production:
  <<: *default
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: <%= ENV["MYSQL_DATABASE"] %>  