default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: kenken3922
  socket: /tmp/mysql.sock 

development:
  <<: *default
  database: mission-forest_development

test:
  <<: *default
  database: mission-forest_test

production:
  url: <%= ENV['DATABASE_URL'] %>
